const currencies = {
  "currencies": [
    { "codigo": "AED", "nombre": "Dirham de los Emiratos Árabes Unidos", "simbolo": "د.إ" },
    { "codigo": "AFN", "nombre": "Afgani afgano", "simbolo": "؋" },
    { "codigo": "ALL", "nombre": "Lek albanés", "simbolo": "L" },
    { "codigo": "AMD", "nombre": "Dram armenio", "simbolo": "֏" },
    { "codigo": "ANG", "nombre": "Florín de las Antillas Neerlandesas", "simbolo": "ƒ" },
    { "codigo": "AOA", "nombre": "Kwanza angoleño", "simbolo": "Kz" },
    { "codigo": "ARS", "nombre": "Peso argentino", "simbolo": "$" },
    { "codigo": "AUD", "nombre": "Dólar australiano", "simbolo": "A$" },
    { "codigo": "AWG", "nombre": "Florín arubeño", "simbolo": "ƒ" },
    { "codigo": "AZN", "nombre": "Manat azerbaiyano", "simbolo": "₼" },
    { "codigo": "BAM", "nombre": "Marco convertible de Bosnia y Herzegovina", "simbolo": "KM" },
    { "codigo": "BBD", "nombre": "Dólar de Barbados", "simbolo": "Bds$" },
    { "codigo": "BDT", "nombre": "Taka bangladesí", "simbolo": "৳" },
    { "codigo": "BGN", "nombre": "Lev búlgaro", "simbolo": "лв" },
    { "codigo": "BHD", "nombre": "Dinar bahreiní", "simbolo": ".د.ب" },
    { "codigo": "BIF", "nombre": "Franco burundés", "simbolo": "Fr" },
    { "codigo": "BMD", "nombre": "Dólar bermudeño", "simbolo": "$" },
    { "codigo": "BND", "nombre": "Dólar de Brunéi", "simbolo": "B$" },
    { "codigo": "BOB", "nombre": "Boliviano", "simbolo": "Bs" },
    { "codigo": "BRL", "nombre": "Real brasileño", "simbolo": "R$" },
    { "codigo": "BSD", "nombre": "Dólar bahameño", "simbolo": "$" },
    { "codigo": "BTN", "nombre": "Ngultrum butanés", "simbolo": "Nu." },
    { "codigo": "BWP", "nombre": "Pula botsuana", "simbolo": "P" },
    { "codigo": "BYN", "nombre": "Rublo bielorruso", "simbolo": "Br" },
    { "codigo": "BZD", "nombre": "Dólar beliceño", "simbolo": "BZ$" },
    { "codigo": "CAD", "nombre": "Dólar canadiense", "simbolo": "C$" },
    { "codigo": "CDF", "nombre": "Franco congoleño", "simbolo": "Fr" },
    { "codigo": "CHF", "nombre": "Franco suizo", "simbolo": "CHF" },
    { "codigo": "CLP", "nombre": "Peso chileno", "simbolo": "$" },
    { "codigo": "CNY", "nombre": "Yuan chino", "simbolo": "¥" },
    { "codigo": "COP", "nombre": "Peso colombiano", "simbolo": "$" },
    { "codigo": "CRC", "nombre": "Colón costarricense", "simbolo": "₡" },
    { "codigo": "CUP", "nombre": "Peso cubano", "simbolo": "$" },
    { "codigo": "CUC", "nombre": "Peso cubano convertible", "simbolo": "$" },
    { "codigo": "CZK", "nombre": "Corona checa", "simbolo": "Kč" },
    { "codigo": "DKK", "nombre": "Corona danesa", "simbolo": "kr" },
    { "codigo": "DOP", "nombre": "Peso dominicano", "simbolo": "$" },
    { "codigo": "DZD", "nombre": "Dinar argelino", "simbolo": "د.ج" },
    { "codigo": "EGP", "nombre": "Libra egipcia", "simbolo": "£" },
    { "codigo": "ERN", "nombre": "Nakfa eritreo", "simbolo": "Nfk" },
    { "codigo": "ETB", "nombre": "Birr etíope", "simbolo": "Br" },
    { "codigo": "EUR", "nombre": "Euro", "simbolo": "€" },
    { "codigo": "FJD", "nombre": "Dólar fiyiano", "simbolo": "FJ$" },
    { "codigo": "FKP", "nombre": "Libra de las Islas Malvinas", "simbolo": "£" },
    { "codigo": "FOK", "nombre": "Corona de las Islas Feroe", "simbolo": "kr" },
    { "codigo": "GBP", "nombre": "Libra esterlina", "simbolo": "£" },
    { "codigo": "GEL", "nombre": "Lari georgiano", "simbolo": "₾" },
    { "codigo": "GHS", "nombre": "Cedi ghanés", "simbolo": "₵" },
    { "codigo": "GIP", "nombre": "Libra gibraltareña", "simbolo": "£" },
    { "codigo": "GMD", "nombre": "Dalasi gambiano", "simbolo": "D" },
    { "codigo": "GNF", "nombre": "Franco guineano", "simbolo": "Fr" },
    { "codigo": "GTQ", "nombre": "Quetzal guatemalteco", "simbolo": "Q" },
    { "codigo": "GYD", "nombre": "Dólar guyanés", "simbolo": "G$" },
    { "codigo": "HKD", "nombre": "Dólar de Hong Kong", "simbolo": "HK$" },
    { "codigo": "HNL", "nombre": "Lempira hondureño", "simbolo": "L" },
    { "codigo": "HRK", "nombre": "Kuna croata", "simbolo": "kn" },
    { "codigo": "HTG", "nombre": "Gourde haitiano", "simbolo": "G" },
    { "codigo": "HUF", "nombre": "Forinto húngaro", "simbolo": "Ft" },
    { "codigo": "IDR", "nombre": "Rupia indonesia", "simbolo": "Rp" },
    { "codigo": "ILS", "nombre": "Nuevo shekel israelí", "simbolo": "₪" },
    { "codigo": "INR", "nombre": "Rupia india", "simbolo": "₹" },
    { "codigo": "IQD", "nombre": "Dinar iraquí", "simbolo": "ع.د" },
    { "codigo": "IRR", "nombre": "Rial iraní", "simbolo": "﷼" },
    { "codigo": "ISK", "nombre": "Corona islandesa", "simbolo": "kr" },
    { "codigo": "JMD", "nombre": "Dólar jamaiquino", "simbolo": "J$" },
    { "codigo": "JOD", "nombre": "Dinar jordano", "simbolo": "د.أ" },
    { "codigo": "JPY", "nombre": "Yen japonés", "simbolo": "¥" },
    { "codigo": "KES", "nombre": "Chelín keniano", "simbolo": "KSh" },
    { "codigo": "KGS", "nombre": "Som kirguís", "simbolo": "с" },
    { "codigo": "KHR", "nombre": "Riel camboyano", "simbolo": "៛" },
    { "codigo": "KPW", "nombre": "Won norcoreano", "simbolo": "₩" },
    { "codigo": "KRW", "nombre": "Won surcoreano", "simbolo": "₩" },
    { "codigo": "KWD", "nombre": "Dinar kuwaití", "simbolo": "د.ك" },
    { "codigo": "KYD", "nombre": "Dólar de las Islas Caimán", "simbolo": "CI$" },
    { "codigo": "KZT", "nombre": "Tenge kazajo", "simbolo": "₸" },
    { "codigo": "LAK", "nombre": "Kip laosiano", "simbolo": "₭" },
    { "codigo": "LBP", "nombre": "Libra libanesa", "simbolo": "ل.ل" },
    { "codigo": "LKR", "nombre": "Rupia de Sri Lanka", "simbolo": "Rs" },
    { "codigo": "LRD", "nombre": "Dólar liberiano", "simbolo": "L$" },
    { "codigo": "LSL", "nombre": "Loti de Lesoto", "simbolo": "L" },
    { "codigo": "LYD", "nombre": "Dinar libio", "simbolo": "ل.د" },
    { "codigo": "MAD", "nombre": "Dirham marroquí", "simbolo": "د.م." },
    { "codigo": "MDL", "nombre": "Leu moldavo", "simbolo": "L" },
    { "codigo": "MGA", "nombre": "Ariary malgache", "simbolo": "Ar" },
    { "codigo": "MKD", "nombre": "Dinar macedonio", "simbolo": "ден" },
    { "codigo": "MMK", "nombre": "Kyat birmano", "simbolo": "K" },
    { "codigo": "MNT", "nombre": "Tugrik mongol", "simbolo": "₮" },
    { "codigo": "MOP", "nombre": "Pataca de Macao", "simbolo": "MOP$" },
    { "codigo": "MRU", "nombre": "Ouguiya mauritana", "simbolo": "UM" },
    { "codigo": "MUR", "nombre": "Rupia mauriciana", "simbolo": "Rs" },
    { "codigo": "MVR", "nombre": "Rufiyaa maldiva", "simbolo": "Rf" },
    { "codigo": "MWK", "nombre": "Kwacha malauí", "simbolo": "MK" },
    { "codigo": "MXN", "nombre": "Peso mexicano", "simbolo": "$" },
    { "codigo": "MYR", "nombre": "Ringgit malayo", "simbolo": "RM" },
    { "codigo": "MZN", "nombre": "Metical mozambiqueño", "simbolo": "MT" },
    { "codigo": "NAD", "nombre": "Dólar namibio", "simbolo": "N$" },
    { "codigo": "NGN", "nombre": "Naira nigeriana", "simbolo": "₦" },
    { "codigo": "NIO", "nombre": "Córdoba nicaragüense", "simbolo": "C$" },
    { "codigo": "NOK", "nombre": "Corona noruega", "simbolo": "kr" },
    { "codigo": "NPR", "nombre": "Rupia nepalí", "simbolo": "Rs" },
    { "codigo": "NZD", "nombre": "Dólar neozelandés", "simbolo": "NZ$" },
    { "codigo": "OMR", "nombre": "Rial omaní", "simbolo": "ر.ع." },
    { "codigo": "PAB", "nombre": "Balboa panameño", "simbolo": "B/." },
    { "codigo": "PEN", "nombre": "Sol peruano", "simbolo": "S/" },
    { "codigo": "PGK", "nombre": "Kina de Papúa Nueva Guinea", "simbolo": "K" },
    { "codigo": "PHP", "nombre": "Peso filipino", "simbolo": "₱" },
    { "codigo": "PKR", "nombre": "Rupia paquistaní", "simbolo": "Rs" },
    { "codigo": "PLN", "nombre": "Zloty polaco", "simbolo": "zł" },
    { "codigo": "PYG", "nombre": "Guaraní paraguayo", "simbolo": "₲" },
    { "codigo": "QAR", "nombre": "Rial catarí", "simbolo": "ر.ق" },
    { "codigo": "RON", "nombre": "Leu rumano", "simbolo": "lei" },
    { "codigo": "RSD", "nombre": "Dinar serbio", "simbolo": "дин." },
    { "codigo": "RUB", "nombre": "Rublo ruso", "simbolo": "₽" },
    { "codigo": "RWF", "nombre": "Franco ruandés", "simbolo": "Fr" },
    { "codigo": "SAR", "nombre": "Riyal saudí", "simbolo": "ر.س" },
    { "codigo": "SBD", "nombre": "Dólar de las Islas Salomón", "simbolo": "SI$" },
    { "codigo": "SCR", "nombre": "Rupia de Seychelles", "simbolo": "₨" },
    { "codigo": "SDG", "nombre": "Libra sudanesa", "simbolo": "ج.س." },
    { "codigo": "SEK", "nombre": "Corona sueca", "simbolo": "kr" },
    { "codigo": "SGD", "nombre": "Dólar de Singapur", "simbolo": "S$" },
    { "codigo": "SHP", "nombre": "Libra de Santa Helena", "simbolo": "£" },
    { "codigo": "SLL", "nombre": "León de Sierra Leona", "simbolo": "Le" },
    { "codigo": "SOS", "nombre": "Chelín somalí", "simbolo": "S" },
    { "codigo": "SRD", "nombre": "Dólar surinamés", "simbolo": "$" },
    { "codigo": "SSP", "nombre": "Libra sursudanesa", "simbolo": "£" },
    { "codigo": "STN", "nombre": "Dobra de Santo Tomé y Príncipe", "simbolo": "Db" },
    { "codigo": "SYP", "nombre": "Libra siria", "simbolo": "£" },
    { "codigo": "SZL", "nombre": "Lilangeni suazi", "simbolo": "E" },
    { "codigo": "THB", "nombre": "Baht tailandés", "simbolo": "฿" },
    { "codigo": "TJS", "nombre": "Somoni tayiko", "simbolo": "SM" },
    { "codigo": "TMT", "nombre": "Manat turcomano", "simbolo": "T" },
    { "codigo": "TND", "nombre": "Dinar tunecino", "simbolo": "د.ت" },
    { "codigo": "TOP", "nombre": "Pa'anga tongano", "simbolo": "T$" },
    { "codigo": "TRY", "nombre": "Lira turca", "simbolo": "₺" },
    { "codigo": "TTD", "nombre": "Dólar de Trinidad y Tobago", "simbolo": "TT$" },
    { "codigo": "TWD", "nombre": "Dólar nuevo taiwanés", "simbolo": "NT$" },
    { "codigo": "TZS", "nombre": "Chelín tanzano", "simbolo": "TSh" },
    { "codigo": "UAH", "nombre": "Grivna ucraniana", "simbolo": "₴" },
    { "codigo": "UGX", "nombre": "Chelín ugandés", "simbolo": "USh" },
    { "codigo": "USD", "nombre": "Dólar estadounidense", "simbolo": "$" },
    { "codigo": "UYU", "nombre": "Peso uruguayo", "simbolo": "$" },
    { "codigo": "UZS", "nombre": "Som uzbeko", "simbolo": "лв" },
    { "codigo": "VEF", "nombre": "Bolívar venezolano", "simbolo": "Bs" },
    { "codigo": "VND", "nombre": "Dong vietnamita", "simbolo": "₫" },
    { "codigo": "VUV", "nombre": "Vatu de Vanuatu", "simbolo": "Vt" },
    { "codigo": "WST", "nombre": "Tala samoano", "simbolo": "WS$" },
    { "codigo": "XAF", "nombre": "Franco CFA de África Central", "simbolo": "Fr" },
    { "codigo": "XAG", "nombre": "Plata (medida)", "simbolo": "oz" },
    { "codigo": "XAU", "nombre": "Oro (medida)", "simbolo": "oz" },
    { "codigo": "XCD", "nombre": "Dólar del Caribe Oriental", "simbolo": "$" },
    { "codigo": "XOF", "nombre": "Franco CFA de África Occidental", "simbolo": "Fr" },
    { "codigo": "XPF", "nombre": "Franco CFP", "simbolo": "Fr" },
    { "codigo": "YER", "nombre": "Rial yemení", "simbolo": "﷼" },
    { "codigo": "ZAR", "nombre": "Rand sudafricano", "simbolo": "R" },
    { "codigo": "ZMW", "nombre": "Kwacha zambiano", "simbolo": "ZK" },
    { "codigo": "ZWL", "nombre": "Dólar zimbabuense", "simbolo": "Z$" },
    { "codigo": "BTC", "nombre": "Bitcoin", "simbolo": "₿" },
    { "codigo": "ETH", "nombre": "Ethereum", "simbolo": "Ξ" },
    { "codigo": "BNB", "nombre": "Binance Coin", "simbolo": "BNB" },
    { "codigo": "XRP", "nombre": "Ripple", "simbolo": "XRP" },
    { "codigo": "SOL", "nombre": "Solana", "simbolo": "SOL" },
    { "codigo": "ADA", "nombre": "Cardano", "simbolo": "₳" },
    { "codigo": "DOT", "nombre": "Polkadot", "simbolo": "DOT" },
  ]
};

export default currencies;