version: 'v2.28.1-desktop.1'

services:
  backend:
    build:
      context: ./backend/
      target: developer
    ports:
      - "127.0.0.1:8000:0.0.0.0:8000"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/docs"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s
    env_file:
      - ./backend/app/.env.develoment
    develop:
      watch:
        - path: ./backend/app
          action: sync
          target: /usr/local/app
        - path: ./backend/requirements.txt
          action: rebuild
          ignore:
            - ./backend/.venv
            - ./backend/Dockerfile
            - ./backend/app/*.md


  web:
    build:
      context: ./frontend/web/
      target: developer
    ports:
        - 5173:5173
    links:
      - backend
    depends_on:
      backend:
        condition: service_healthy
    develop:
      watch:
        - path: ./frontend/web/app/src
          action: sync
          target: /usr/src/app/src
        - path: ./frontend/web/app/package.json
          action: rebuild
          ignore:
            - ./frontend/web/app/public
            - ./frontend/web/app/*.md
            - ./frontend/web/app/*.html
            - ./frontend/web/app/*.json
            - ./frontend/web/app/*.ts
            - ./frontend/web/app/*.js
            - ./frontend/web/app/*.yaml
            - ./frontend/web/app/.gitignore
            - ./frontend/web/app/node_modules/


  # movil:
  #   build: ./frontend/movil/
  #   ports:
  #       - 8081:8081
  #   links:
  #     - backend
  #   depends_on:
  #     backend:
  #       condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    volumes:
      - data_personal_finance:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh", "-c", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

volumes:
  data_personal_finance: